version: '3'
services:
  blog-server:
    build: 
      context: .
      dockerfile: Dockerfile.blog
    container_name: blog-server
    networks:
      company_net:
        ipv4_address: 10.0.0.100

  dns-server:
    build:
      context: .
      dockerfile: Dockerfile.dns_server
    container_name: dns-server
    networks:
      company_net:
        ipv4_address: 10.0.0.53

  test-server:
    image: alpine:3.19
    container_name: test-server
    networks:
      company_net:
        ipv4_address: 10.0.0.54
    command: tail -f /dev/null

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client
    dns: 10.0.0.54
    dns_search: []
    dns_opt:
      - ndots:1
    command: tail -f /dev/null
    networks:
      company_net:
        ipv4_address: 10.0.0.10

networks:
  company_net:
    ipam:
      config:
        - subnet: 10.0.0.0/24