[book]
authors = ["Mohammad Durrani"]
language = "en"
src = "src"
title = "Practical Tools For Efficient Development"

[preprocessor]
[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
